server:
  servlet:
    context-path: /lemon
  port: 6789
spring:
  datasource:
    url: jdbc:mysql://122.51.240.193:3306/Demo3?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: info
    com.lemon.mapper: trace

